### ISSUE TITLE
Please help, i get this error

### ISSUE THREAD

**Issue by v0RcE1234** [lnxcz/nitro-generator#22]
Traceback (most recent call last):
  File "C:\Users\rohan_2tq3dn2\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\rohan_2tq3dn2\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "C:\Users\rohan_2tq3dn2\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "C:\Users\rohan_2tq3dn2\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\rohan_2tq3dn2\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\util\ssl_.py", line 428, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\Users\rohan_2tq3dn2\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\util\ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\rohan_2tq3dn2\AppData\Local\Programs\Python\Python38-32\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\rohan_2tq3dn2\AppData\Local\Programs\Python\Python38-32\lib\ssl.py", line 1040, in _create  
    self.do_handshake()
  File "C:\Users\rohan_2tq3dn2\AppData\Local\Programs\Python\Python38-32\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1108)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rohan_2tq3dn2\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\rohan_2tq3dn2\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\rohan_2tq3dn2\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.proxyscrape.com', port=443): Max retries exceeded with url: /?request=displayproxies&proxytype=http&timeout=1500&ssl=yes (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1108)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\rohan_2tq3dn2\Desktop\nitro-generator-master\generator\main.py", line 47, in <module>       
    scrape()
  File "c:\Users\rohan_2tq3dn2\Desktop\nitro-generator-master\generator\main.py", line 30, in scrape
    r = requests.get('https://api.proxyscrape.com/?request=displayproxies&proxytype=http&timeout=1500&ssl=yes')
  File "C:\Users\rohan_2tq3dn2\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\api.py", 
line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\rohan_2tq3dn2\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\api.py", 
line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\rohan_2tq3dn2\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\rohan_2tq3dn2\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\rohan_2tq3dn2\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.proxyscrape.com', port=443): Max retries exceeded with url: /?request=displayproxies&proxytype=http&timeout=1500&ssl=yes (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1108)')))

**Comment by DumbGameMaker** [comment]
don't use this you won't get nitro. the chances of a classic code being correct is 1 in 4e+62 (4 with 62 0's), even lower for boost. for context: the chances of getting a classic code is lower than winning the lottery and being struck by lightning within 2 hours of each other
