### ISSUE TITLE
Fix this

### ISSUE THREAD

**Issue by RXNationGMG** [lnxcz/nitro-generator#30]
Fix this rn
```js
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/urllib3/connection.py", line 362, in connect
    self.sock = ssl_wrap_socket(
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 386, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/data/data/com.termux/files/usr/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/data/data/com.termux/files/usr/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/data/data/com.termux/files/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.proxyscrape.com', port=443): Max retries exceeded with url: /?request=displayproxies&proxytype=http&timeout=1500&ssl=yes (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/nitro-generator/generator/main.py", line 47, in <module>
    scrape()
  File "/data/data/com.termux/files/home/nitro-generator/generator/main.py", line 30, in scrape
    r = requests.get('https://api.proxyscrape.com/?request=displayproxies&proxytype=http&timeout=1500&ssl=yes')
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.proxyscrape.com', port=443): Max retries exceeded with url: /?request=displayproxies&proxytype=http&timeout=1500&ssl=yes (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))
```
:(

**Comment by unspecifiedhuman** [comment]
This error is only on termux (as far as i'm aware) so if you have a computer, use that. I would recommend linux subsystem for windows as this allows you to use bash.

**Comment by DR34M-M4K3R** [comment]
i find you a little bit rude by coming here, not even knowing what's saying the error, and literally saying "fix this rn". But @unspecifiedhuman  answered right. Please be concious of your courtesy while opening an issue.
